package com.list.pojo;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.junit.Test;

import java.io.Serializable;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class CommonList implements Serializable {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commonlist.id
     *
     * @mbg.generated Wed Sep 07 18:49:41 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commonlist.content
     *
     * @mbg.generated Wed Sep 07 18:49:41 CST 2022
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commonlist.create_date
     *
     * @mbg.generated Wed Sep 07 18:49:41 CST 2022
     */
    private String createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commonlist.finish_date
     *
     * @mbg.generated Wed Sep 07 18:49:41 CST 2022
     */
    private String finishDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commonlist.status
     *
     * @mbg.generated Wed Sep 07 18:49:41 CST 2022
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commonlist.id
     *
     * @return the value of commonlist.id
     *
     * @mbg.generated Wed Sep 07 18:49:41 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commonlist.id
     *
     * @param id the value for commonlist.id
     *
     * @mbg.generated Wed Sep 07 18:49:41 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commonlist.content
     *
     * @return the value of commonlist.content
     *
     * @mbg.generated Wed Sep 07 18:49:41 CST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commonlist.content
     *
     * @param content the value for commonlist.content
     *
     * @mbg.generated Wed Sep 07 18:49:41 CST 2022
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commonlist.create_date
     *
     * @return the value of commonlist.create_date
     *
     * @mbg.generated Wed Sep 07 18:49:41 CST 2022
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commonlist.create_date
     *
     * @param createDate the value for commonlist.create_date
     *
     * @mbg.generated Wed Sep 07 18:49:41 CST 2022
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate == null ? null : createDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commonlist.finish_date
     *
     * @return the value of commonlist.finish_date
     *
     * @mbg.generated Wed Sep 07 18:49:41 CST 2022
     */
    public String getFinishDate() {
        return finishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commonlist.finish_date
     *
     * @param finishDate the value for commonlist.finish_date
     *
     * @mbg.generated Wed Sep 07 18:49:41 CST 2022
     */
    public void setFinishDate(String finishDate) {
        this.finishDate = finishDate == null ? null : finishDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commonlist.status
     *
     * @return the value of commonlist.status
     *
     * @mbg.generated Wed Sep 07 18:49:41 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commonlist.status
     *
     * @param status the value for commonlist.status
     *
     * @mbg.generated Wed Sep 07 18:49:41 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}