package com.list.pojo;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class DailyList implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dailylist.id
     *
     * @mbg.generated Fri Sep 09 13:33:10 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dailylist.create_date
     *
     * @mbg.generated Fri Sep 09 13:33:10 CST 2022
     */
    private String createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dailylist.id
     *
     * @return the value of dailylist.id
     *
     * @mbg.generated Fri Sep 09 13:33:10 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dailylist.id
     *
     * @param id the value for dailylist.id
     *
     * @mbg.generated Fri Sep 09 13:33:10 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dailylist.create_date
     *
     * @return the value of dailylist.create_date
     *
     * @mbg.generated Fri Sep 09 13:33:10 CST 2022
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dailylist.create_date
     *
     * @param createDate the value for dailylist.create_date
     *
     * @mbg.generated Fri Sep 09 13:33:10 CST 2022
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate == null ? null : createDate.trim();
    }
}