package com.list.pojo;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class NetDisk implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column netdisk.id
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column netdisk.uuid
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column netdisk.file_name
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column netdisk.desc
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column netdisk.type_name
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column netdisk.size
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    private Integer size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column netdisk.file_path
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    private String filePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column netdisk.upload_date
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    private String uploadDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column netdisk.download_count
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    private Integer downloadCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column netdisk.id
     *
     * @return the value of netdisk.id
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column netdisk.id
     *
     * @param id the value for netdisk.id
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column netdisk.uuid
     *
     * @return the value of netdisk.uuid
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column netdisk.uuid
     *
     * @param uuid the value for netdisk.uuid
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column netdisk.file_name
     *
     * @return the value of netdisk.file_name
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column netdisk.file_name
     *
     * @param fileName the value for netdisk.file_name
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column netdisk.desc
     *
     * @return the value of netdisk.desc
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column netdisk.desc
     *
     * @param desc the value for netdisk.desc
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column netdisk.type_name
     *
     * @return the value of netdisk.type_name
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column netdisk.type_name
     *
     * @param typeName the value for netdisk.type_name
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column netdisk.size
     *
     * @return the value of netdisk.size
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column netdisk.size
     *
     * @param size the value for netdisk.size
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column netdisk.file_path
     *
     * @return the value of netdisk.file_path
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column netdisk.file_path
     *
     * @param filePath the value for netdisk.file_path
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column netdisk.upload_date
     *
     * @return the value of netdisk.upload_date
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    public String getUploadDate() {
        return uploadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column netdisk.upload_date
     *
     * @param uploadDate the value for netdisk.upload_date
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    public void setUploadDate(String uploadDate) {
        this.uploadDate = uploadDate == null ? null : uploadDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column netdisk.download_count
     *
     * @return the value of netdisk.download_count
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    public Integer getDownloadCount() {
        return downloadCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column netdisk.download_count
     *
     * @param downloadCount the value for netdisk.download_count
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    public void setDownloadCount(Integer downloadCount) {
        this.downloadCount = downloadCount;
    }
}