package com.list.mapper;

import com.list.pojo.CommonList;
import com.list.pojo.CommonListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommonListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commonlist
     *
     * @mbg.generated Wed Sep 07 18:49:41 CST 2022
     */
    long countByExample(CommonListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commonlist
     *
     * @mbg.generated Wed Sep 07 18:49:41 CST 2022
     */
    int deleteByExample(CommonListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commonlist
     *
     * @mbg.generated Wed Sep 07 18:49:41 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commonlist
     *
     * @mbg.generated Wed Sep 07 18:49:41 CST 2022
     */
    int insert(CommonList row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commonlist
     *
     * @mbg.generated Wed Sep 07 18:49:41 CST 2022
     */
    int insertSelective(CommonList row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commonlist
     *
     * @mbg.generated Wed Sep 07 18:49:41 CST 2022
     */
    List<CommonList> selectByExample(CommonListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commonlist
     *
     * @mbg.generated Wed Sep 07 18:49:41 CST 2022
     */
    CommonList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commonlist
     *
     * @mbg.generated Wed Sep 07 18:49:41 CST 2022
     */
    int updateByExampleSelective(@Param("row") CommonList row, @Param("example") CommonListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commonlist
     *
     * @mbg.generated Wed Sep 07 18:49:41 CST 2022
     */
    int updateByExample(@Param("row") CommonList row, @Param("example") CommonListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commonlist
     *
     * @mbg.generated Wed Sep 07 18:49:41 CST 2022
     */
    int updateByPrimaryKeySelective(CommonList row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commonlist
     *
     * @mbg.generated Wed Sep 07 18:49:41 CST 2022
     */
    int updateByPrimaryKey(CommonList row);
}