package com.list.mapper;

import com.list.pojo.DailyListContent;
import com.list.pojo.DailyListContentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DailyListContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dailylistcontent
     *
     * @mbg.generated Fri Sep 09 13:33:10 CST 2022
     */
    long countByExample(DailyListContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dailylistcontent
     *
     * @mbg.generated Fri Sep 09 13:33:10 CST 2022
     */
    int deleteByExample(DailyListContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dailylistcontent
     *
     * @mbg.generated Fri Sep 09 13:33:10 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dailylistcontent
     *
     * @mbg.generated Fri Sep 09 13:33:10 CST 2022
     */
    int insert(DailyListContent row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dailylistcontent
     *
     * @mbg.generated Fri Sep 09 13:33:10 CST 2022
     */
    int insertSelective(DailyListContent row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dailylistcontent
     *
     * @mbg.generated Fri Sep 09 13:33:10 CST 2022
     */
    List<DailyListContent> selectByExample(DailyListContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dailylistcontent
     *
     * @mbg.generated Fri Sep 09 13:33:10 CST 2022
     */
    DailyListContent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dailylistcontent
     *
     * @mbg.generated Fri Sep 09 13:33:10 CST 2022
     */
    int updateByExampleSelective(@Param("row") DailyListContent row, @Param("example") DailyListContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dailylistcontent
     *
     * @mbg.generated Fri Sep 09 13:33:10 CST 2022
     */
    int updateByExample(@Param("row") DailyListContent row, @Param("example") DailyListContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dailylistcontent
     *
     * @mbg.generated Fri Sep 09 13:33:10 CST 2022
     */
    int updateByPrimaryKeySelective(DailyListContent row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dailylistcontent
     *
     * @mbg.generated Fri Sep 09 13:33:10 CST 2022
     */
    int updateByPrimaryKey(DailyListContent row);
}