package com.list.mapper;

import com.list.pojo.Dlri;
import com.list.pojo.DlriExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DlriMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlri
     *
     * @mbg.generated Sun Sep 18 13:43:49 CST 2022
     */
    long countByExample(DlriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlri
     *
     * @mbg.generated Sun Sep 18 13:43:49 CST 2022
     */
    int deleteByExample(DlriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlri
     *
     * @mbg.generated Sun Sep 18 13:43:49 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlri
     *
     * @mbg.generated Sun Sep 18 13:43:49 CST 2022
     */
    int insert(Dlri row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlri
     *
     * @mbg.generated Sun Sep 18 13:43:49 CST 2022
     */
    int insertSelective(Dlri row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlri
     *
     * @mbg.generated Sun Sep 18 13:43:49 CST 2022
     */
    List<Dlri> selectByExample(DlriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlri
     *
     * @mbg.generated Sun Sep 18 13:43:49 CST 2022
     */
    Dlri selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlri
     *
     * @mbg.generated Sun Sep 18 13:43:49 CST 2022
     */
    int updateByExampleSelective(@Param("row") Dlri row, @Param("example") DlriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlri
     *
     * @mbg.generated Sun Sep 18 13:43:49 CST 2022
     */
    int updateByExample(@Param("row") Dlri row, @Param("example") DlriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlri
     *
     * @mbg.generated Sun Sep 18 13:43:49 CST 2022
     */
    int updateByPrimaryKeySelective(Dlri row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dlri
     *
     * @mbg.generated Sun Sep 18 13:43:49 CST 2022
     */
    int updateByPrimaryKey(Dlri row);
}