package com.list.mapper;

import com.list.pojo.NetDisk;
import com.list.pojo.NetDiskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NetDiskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table netdisk
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    long countByExample(NetDiskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table netdisk
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    int deleteByExample(NetDiskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table netdisk
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table netdisk
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    int insert(NetDisk row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table netdisk
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    int insertSelective(NetDisk row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table netdisk
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    List<NetDisk> selectByExample(NetDiskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table netdisk
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    NetDisk selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table netdisk
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    int updateByExampleSelective(@Param("row") NetDisk row, @Param("example") NetDiskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table netdisk
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    int updateByExample(@Param("row") NetDisk row, @Param("example") NetDiskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table netdisk
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    int updateByPrimaryKeySelective(NetDisk row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table netdisk
     *
     * @mbg.generated Fri Sep 16 13:06:45 CST 2022
     */
    int updateByPrimaryKey(NetDisk row);
}